# To commentdecomment on Notepad++, use Ctrl+K / Ctrk+Q
# Alt + 3 repli les sections
 
###########################################################################
# Version scale avec nodered (15 max) / influxdb(1) / grafana (15 max)
# docker-compose up -d --scale grafana=3 --scale nodered=3 --scale influxdb=1
###########################################################################
version: "3.5"
services:
  nodered:
    build: ./nodered-rpi-workshop
    networks:
      - LoraNetwork
    ports:
      - "1880-1894:1880"
    restart: on-failure 
     
  influxdb:
    image: "influxdb"
    networks:
      - LoraNetwork
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=maBase
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=,;:!jklm
    restart: on-failure

  grafana:
    image: "grafana/grafana"
    networks:
      - LoraNetwork
    ports:
      - "3000-3014:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=,;:!jklm
    
    restart: on-failure
networks:
  LoraNetwork:
    name: loraNetwork  




